# Generated by Django 5.2.1 on 2025-05-19 16:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitalpostureanalysis',
            name='report_file',
        ),
        migrations.AddField(
            model_name='digitalpostureanalysis',
            name='analysis_recommendations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='digitalpostureanalysis',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='digitalpostureanalysis',
            name='analysis_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='digitalpostureanalysis',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='users.clientprofile'),
        ),
        migrations.AlterField(
            model_name='digitalpostureanalysis',
            name='metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='digitalpostureanalysis',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_set', to='analysis.digitalpostureanalysis'),
        ),
    ]
